server:
  port: 7004
spring:
  application:
    name: gateway-service
    instance_id: gw-1
  main:
    web-application-type: reactive
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-service
      override-system-properties: true
    consul:
      host: 192.168.102.82
      port: 8099
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${spring.application.instance_id:3.4.1}
        register: true
        health-check-critical-timeout: 10s
        heartbeat:
          enabled: true
  config:
    import: 'optional:configserver:'

  profiles:
    active: default,dev,spring
#logging:
#  level:
#    com.tiddev.apigateway.ratelimit.MyRedisRateLimiter: debug
